// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.message.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaaf44d000ff2bc7, []int{0}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaaf44d000ff2bc7, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResult struct {
	Ok                   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data                 *AccessToken `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaaf44d000ff2bc7, []int{2}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *LoginResult) GetData() *AccessToken {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AccessToken)(nil), "rpc.AccessToken")
	proto.RegisterType((*Credentials)(nil), "rpc.Credentials")
	proto.RegisterType((*LoginResult)(nil), "rpc.LoginResult")
}

func init() { proto.RegisterFile("user.message.proto", fileDescriptor_aaaf44d000ff2bc7) }

var fileDescriptor_aaaf44d000ff2bc7 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x6b, 0xc3, 0x30,
	0x10, 0xc5, 0xb1, 0x5b, 0x8a, 0x7b, 0x2a, 0xa5, 0x68, 0x32, 0x9d, 0x5a, 0x93, 0x21, 0x93, 0x08,
	0xc9, 0x27, 0x08, 0x26, 0x5b, 0x26, 0x91, 0x3d, 0x5c, 0xe4, 0xc3, 0x18, 0xdb, 0x92, 0xd0, 0xc9,
	0xe4, 0xeb, 0x07, 0x2b, 0x7f, 0xc7, 0x1f, 0xbf, 0x77, 0x8f, 0x7b, 0x20, 0x27, 0xa6, 0xa0, 0x46,
	0x62, 0xc6, 0x96, 0x94, 0x0f, 0x2e, 0x3a, 0xf9, 0x16, 0xbc, 0xa9, 0x56, 0x20, 0xb6, 0xc6, 0x10,
	0xf3, 0xc1, 0xf5, 0x64, 0xe5, 0x3f, 0x7c, 0x61, 0xc2, 0x63, 0x9c, 0xb9, 0xcc, 0xfe, 0xb2, 0xe5,
	0xa7, 0x16, 0xf8, 0x8c, 0x54, 0x3b, 0x10, 0x75, 0xa0, 0x86, 0x6c, 0xec, 0x70, 0x60, 0xf9, 0x0b,
	0xc5, 0xdc, 0x6d, 0x71, 0xa4, 0x5b, 0xfa, 0xc1, 0xb3, 0xf3, 0xc8, 0x7c, 0x76, 0xa1, 0x29, 0xf3,
	0xab, 0xbb, 0x73, 0x55, 0x83, 0xd8, 0xbb, 0xb6, 0xb3, 0x9a, 0x78, 0x1a, 0xa2, 0xfc, 0x86, 0xdc,
	0xf5, 0xa9, 0xa0, 0xd0, 0xb9, 0xeb, 0xe5, 0x02, 0xde, 0x1b, 0x8c, 0x98, 0xce, 0xc4, 0xfa, 0x47,
	0x05, 0x6f, 0xd4, 0xcb, 0xa3, 0x3a, 0xd9, 0xd3, 0x47, 0x5a, 0xb2, 0xb9, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xa8, 0x36, 0x78, 0x88, 0xdf, 0x00, 0x00, 0x00,
}
