// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/user.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessToken struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}
func (*AccessToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_a808c2e4b16109f3, []int{0}
}

func (m *AccessToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessToken.Unmarshal(m, b)
}
func (m *AccessToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessToken.Marshal(b, m, deterministic)
}
func (m *AccessToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessToken.Merge(m, src)
}
func (m *AccessToken) XXX_Size() int {
	return xxx_messageInfo_AccessToken.Size(m)
}
func (m *AccessToken) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessToken.DiscardUnknown(m)
}

var xxx_messageInfo_AccessToken proto.InternalMessageInfo

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_a808c2e4b16109f3, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResult struct {
	Ok                   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data                 *AccessToken `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResult) Reset()         { *m = LoginResult{} }
func (m *LoginResult) String() string { return proto.CompactTextString(m) }
func (*LoginResult) ProtoMessage()    {}
func (*LoginResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a808c2e4b16109f3, []int{2}
}

func (m *LoginResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResult.Unmarshal(m, b)
}
func (m *LoginResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResult.Marshal(b, m, deterministic)
}
func (m *LoginResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResult.Merge(m, src)
}
func (m *LoginResult) XXX_Size() int {
	return xxx_messageInfo_LoginResult.Size(m)
}
func (m *LoginResult) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResult.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResult proto.InternalMessageInfo

func (m *LoginResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *LoginResult) GetData() *AccessToken {
	if m != nil {
		return m.Data
	}
	return nil
}

type FormRegister struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastNane             string   `protobuf:"bytes,2,opt,name=last_nane,json=lastNane,proto3" json:"last_nane,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FormRegister) Reset()         { *m = FormRegister{} }
func (m *FormRegister) String() string { return proto.CompactTextString(m) }
func (*FormRegister) ProtoMessage()    {}
func (*FormRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_a808c2e4b16109f3, []int{3}
}

func (m *FormRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FormRegister.Unmarshal(m, b)
}
func (m *FormRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FormRegister.Marshal(b, m, deterministic)
}
func (m *FormRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FormRegister.Merge(m, src)
}
func (m *FormRegister) XXX_Size() int {
	return xxx_messageInfo_FormRegister.Size(m)
}
func (m *FormRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_FormRegister.DiscardUnknown(m)
}

var xxx_messageInfo_FormRegister proto.InternalMessageInfo

func (m *FormRegister) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *FormRegister) GetLastNane() string {
	if m != nil {
		return m.LastNane
	}
	return ""
}

func (m *FormRegister) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *FormRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FormRegister) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *FormRegister) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterResult struct {
	Ok                   bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data                 *AccessToken `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterResult) Reset()         { *m = RegisterResult{} }
func (m *RegisterResult) String() string { return proto.CompactTextString(m) }
func (*RegisterResult) ProtoMessage()    {}
func (*RegisterResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a808c2e4b16109f3, []int{4}
}

func (m *RegisterResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResult.Unmarshal(m, b)
}
func (m *RegisterResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResult.Marshal(b, m, deterministic)
}
func (m *RegisterResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResult.Merge(m, src)
}
func (m *RegisterResult) XXX_Size() int {
	return xxx_messageInfo_RegisterResult.Size(m)
}
func (m *RegisterResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResult.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResult proto.InternalMessageInfo

func (m *RegisterResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *RegisterResult) GetData() *AccessToken {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateUserData struct {
	Data                 *FormRegister `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateUserData) Reset()         { *m = UpdateUserData{} }
func (m *UpdateUserData) String() string { return proto.CompactTextString(m) }
func (*UpdateUserData) ProtoMessage()    {}
func (*UpdateUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a808c2e4b16109f3, []int{5}
}

func (m *UpdateUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserData.Unmarshal(m, b)
}
func (m *UpdateUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserData.Marshal(b, m, deterministic)
}
func (m *UpdateUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserData.Merge(m, src)
}
func (m *UpdateUserData) XXX_Size() int {
	return xxx_messageInfo_UpdateUserData.Size(m)
}
func (m *UpdateUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserData.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserData proto.InternalMessageInfo

func (m *UpdateUserData) GetData() *FormRegister {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*AccessToken)(nil), "message.AccessToken")
	proto.RegisterType((*Credentials)(nil), "message.Credentials")
	proto.RegisterType((*LoginResult)(nil), "message.LoginResult")
	proto.RegisterType((*FormRegister)(nil), "message.FormRegister")
	proto.RegisterType((*RegisterResult)(nil), "message.RegisterResult")
	proto.RegisterType((*UpdateUserData)(nil), "message.UpdateUserData")
}

func init() { proto.RegisterFile("message/user.proto", fileDescriptor_a808c2e4b16109f3) }

var fileDescriptor_a808c2e4b16109f3 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4b, 0x4b, 0xf3, 0x40,
	0x14, 0x25, 0xfd, 0xfa, 0xbc, 0x29, 0x5d, 0x0c, 0xfd, 0x20, 0x54, 0x05, 0xcd, 0xaa, 0x2e, 0x6c,
	0x45, 0x97, 0xae, 0x7c, 0x83, 0x48, 0x17, 0xc1, 0x6e, 0xdc, 0x94, 0xdb, 0xce, 0x35, 0x86, 0x26,
	0x33, 0x61, 0xee, 0x14, 0x7f, 0x9b, 0xff, 0x4e, 0x32, 0x49, 0x6a, 0xba, 0x76, 0x79, 0x5e, 0xc3,
	0xb9, 0x87, 0x01, 0x91, 0x11, 0x33, 0xc6, 0x34, 0xdf, 0x31, 0x99, 0x59, 0x6e, 0xb4, 0xd5, 0xa2,
	0x57, 0x71, 0xe1, 0x25, 0xf8, 0xb7, 0x9b, 0x0d, 0x31, 0xbf, 0xe9, 0x2d, 0x29, 0x71, 0x06, 0x43,
	0x74, 0x70, 0x65, 0x0b, 0x1c, 0x78, 0xa7, 0xde, 0x74, 0x10, 0xf9, 0xf8, 0x6b, 0x09, 0x1f, 0xc1,
	0xbf, 0x37, 0x24, 0x49, 0xd9, 0x04, 0x53, 0x16, 0x13, 0xe8, 0x17, 0xef, 0x2a, 0xcc, 0xa8, 0x72,
	0xef, 0x71, 0xa1, 0xe5, 0xc8, 0xfc, 0xa5, 0x8d, 0x0c, 0x5a, 0xa5, 0x56, 0xe3, 0xf0, 0x19, 0xfc,
	0x57, 0x1d, 0x27, 0x2a, 0x22, 0xde, 0xa5, 0x56, 0x8c, 0xa0, 0xa5, 0xb7, 0xee, 0x81, 0x7e, 0xd4,
	0xd2, 0x5b, 0x31, 0x85, 0xb6, 0x44, 0x8b, 0x2e, 0xe6, 0x5f, 0x8d, 0x67, 0x55, 0xdf, 0x59, 0xa3,
	0x6c, 0xe4, 0x1c, 0xe1, 0xb7, 0x07, 0xc3, 0x27, 0x6d, 0xb2, 0x88, 0xe2, 0x84, 0x2d, 0x19, 0x71,
	0x02, 0xf0, 0x91, 0x18, 0xb6, 0xab, 0x46, 0xa7, 0x81, 0x63, 0x16, 0x45, 0xa9, 0x23, 0x18, 0xa4,
	0xe8, 0x54, 0x45, 0x75, 0xab, 0x82, 0x58, 0xa0, 0x22, 0x31, 0x86, 0x0e, 0x65, 0x98, 0xa4, 0xc1,
	0x3f, 0x27, 0x94, 0xe0, 0xe0, 0x8e, 0xf6, 0xe1, 0x1d, 0xc5, 0x62, 0xf9, 0xa7, 0x56, 0xb4, 0x52,
	0xbb, 0x6c, 0x4d, 0x26, 0xe8, 0x94, 0x8b, 0x39, 0x6e, 0xe1, 0x28, 0x11, 0x40, 0x0f, 0xa5, 0x34,
	0xc4, 0x1c, 0x74, 0x9d, 0x5a, 0xc3, 0xf0, 0x05, 0x46, 0x75, 0xed, 0x3f, 0xef, 0x70, 0x03, 0xa3,
	0x65, 0x2e, 0xd1, 0xd2, 0x92, 0xc9, 0x3c, 0xa0, 0x45, 0x71, 0x5e, 0x65, 0x3d, 0x97, 0xfd, 0xbf,
	0xcf, 0x36, 0xd7, 0x2a, 0xc3, 0x77, 0xc7, 0xef, 0x13, 0x49, 0x99, 0x8e, 0x4d, 0xbe, 0x99, 0xbb,
	0x1f, 0x72, 0x11, 0x93, 0x9a, 0x57, 0x81, 0x75, 0xd7, 0x51, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xce, 0x5c, 0xd0, 0x21, 0x4a, 0x02, 0x00, 0x00,
}
